import streamlit as st
st.set_page_config(layout='wide')
st.title("Sentiment Analysis Project")
st.text("hello")
st.write("hello")
st.success("hello")
st.warning("hello")
st.error("hello")
st.sidebar.image("926015_passport_photo.PNG")
st.sidebar.title("About us")
st.sidebar.text("we are developing ml projects based on NLP in LN AI Academy")
st.sidebar.title("About Projects")
st.sidebar.text("This project reprents sentiments of given text")
st.sidebar.title("Contact us")
st.sidebar.text("+916283008506")
